### PR TITLE
rewrite HttpClient with request package

### PR DESCRIPTION
**Pull request by wenzowski**
Necessary to support https.

### CODE REVIEW

**Comment by wenzowski** [comment]
reference: a [fairly well](https://circle-artifacts.com/gh/wenzowski/dialogue-map/128/artifacts/0/home/ubuntu/dialogue-map/coverage/lcov-report/server/backside/index.html) tested [driver](https://github.com/wenzowski/dialogue-map/blob/feature/backside/src/server/backside/BacksideDriver.js)

**Comment by KnowledgeGarden** [comment]
I am good with whatever you decide!

**Comment by wenzowski** [comment]
@KnowledgeGarden righto
driver appears in wenzowski/dialogue-map#32

**Comment by wenzowski** [comment]
rebased and good for merge

note that you can `require("../config/config.json")` rather than doing all that async `fs` stuff

**Comment by KnowledgeGarden** [comment]
My jpgamebranch on my TQPortalKS is homing in on something well worth merging to master and fusing with this.What do you think?

**Comment by wenzowski** [comment]
I'm happy to rebase this on that if it makes things easier.

**Comment by KnowledgeGarden** [comment]
Should KS be merged from my branch before that?

**Comment by wenzowski** [comment]
Won't matter

**Comment by KnowledgeGarden** [comment]
Then, proceed as you see fit!

**Pull request closed without merging**
